FROM node:20-slim AS builder

WORKDIR /tmp
COPY index.js index.js
COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install

FROM node:20-slim as runner

WORKDIR /tmp
COPY --from=builder /tmp/node_modules node_modules
COPY --from=builder /tmp/index.js index.js

EXPOSE 3000

CMD node index.js
